apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: daily-soc2-inventory
spec:
  reportType: inventory
  endpoints:
    namespaces:
      names:
        - hipstershop
  schedule: 8 6 * * *