apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: daily-soc2-network-access
spec:
  reportType: network-access
  endpoints:
    namespaces:
      names:
        - hipstershop
  schedule: 0 1 * * *